### ISSUE TITLE
Failure to build due to missing declaration

### ISSUE THREAD

**Issue by samimseih** [rjuju/pg_shared_plans#4] opened 2022-06-09 02:39 UTC
Cloned the repo and ran a make install, which failed with:
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -g -O2 -fPIC -I. -I./ -I/home/ec2-user/pg1/pghome/include/postgresql/server -I/home/ec2-user/pg1/pghome/include/postgresql/internal  -D_GNU_SOURCE   -c -o pg_shared_plans.o pg_shared_plans.c
pg_shared_plans.c: In function ‘_PG_init’:
pg_shared_plans.c:385:2: error: ‘prev_shmem_request_hook’ undeclared (first use in this function); did you mean ‘shmem_request_hook’?
  prev_shmem_request_hook = shmem_request_hook;
  ^~~~~~~~~~~~~~~~~~~~~~~
  shmem_request_hook
pg_shared_plans.c:385:2: note: each undeclared identifier is reported only once for each function it appears in
pg_shared_plans.c: In function ‘pgsp_shmem_request’:
pg_shared_plans.c:409:6: error: ‘prev_shmem_request_hook’ undeclared (first use in this function); did you mean ‘shmem_request_hook’?
  if (prev_shmem_request_hook)
      ^~~~~~~~~~~~~~~~~~~~~~~
      shmem_request_hook
pg_shared_plans.c:410:3: warning: implicit declaration of function ‘prev_shmem_request_hook’; did you mean ‘shmem_request_hook’? [-Wimplicit-function-declaration]
   prev_shmem_request_hook();
   ^~~~~~~~~~~~~~~~~~~~~~~
   shmem_request_hook
```
After adding the proper varilable declaration, I was able to build.
```
diff --git a/pg_shared_plans.c b/pg_shared_plans.c
index 1467ee6..24dc6d5 100644
--- a/pg_shared_plans.c
+++ b/pg_shared_plans.c
@@ -113,6 +113,7 @@ typedef struct pgspWalkerContext

 /* Saved hook values in case of unload */
 static shmem_startup_hook_type prev_shmem_startup_hook = NULL;
+static shmem_request_hook_type prev_shmem_request_hook = NULL;
 static planner_hook_type prev_planner_hook = NULL;
 static ProcessUtility_hook_type prev_ProcessUtility = NULL;
```

Regards,

Sami Imseih
Amazon Web Services (simseih@amazon.com)

**Comment by rjuju** [comment] 2022-06-09 03:08
Hi,

Thanks for the report.  The declaration needs to be done for pg 15+ only, as in https://github.com/rjuju/pg_shared_plans/commit/6d0c416827e69fc3b53804dcd3c2694f0e5dd770.

Note that this is an experimental project.  Apparently the workaround to detect significant targetlist alias doesn't work anymore and I just realize that there are some gotchas with the GUC needed to be setup for the extension regression tests to pass.  I will try to fix that shortly.

**Comment by rjuju** [comment] 2022-06-09 07:55
FTR I push a patch to fix most of the regression test failures, but the targetlist problem for json-like plans still fail, I'm not sure why yet.

**Comment by rjuju** [comment] 2022-06-23 14:12
I had some time to look a bit more into the targetlist alias diff, and this is actually due to upstream 205214c8b8ccc40b64f9dad4061f12c4dc28fefd, committed 3 months ago.

I fixed the regression test to use a subquery and make sure they do see the alaises rather than the column names, so all regression tests are now back to green, up to current pg15 beta.

**Closed by rjuju** 2022-06-23 14:12 UTC
